name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  publishpath: './publish'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Release -o ${{ env.publishpath }}
    - name: Azure Functions Action
      uses: Azure/functions-action@v1.4.4
      with:
        # Name of the Azure Function App
        app-name: func-dlh-demo
        # Path to package or folder. *.zip or a folder to deploy
        package: ${{ env.publishpath }}
        # Publish profile (*.publishsettings) file contents with web deploy secrets
        publish-profile: ${{ secrets.AZURE_FUNC_PUBLISH_PROFILE }}
       
